composefs/tests: More flexibility for insecure UKI testing
Update the CI matrix to include `seal_state` and `boot_type`. This does
not increase our matrix, but only rearranges it to be a bit more
meaningful. Earlier even when testing "insecure UKI", it still showed up
as "composefs-sealeduki-sdboot" which is incorrect.

This also allows us flexibility to, in future, test grub + UKI which is
disabled currently.

Update Justfile and the Dockerfile to make use of these new arguments.
Now we only sign the UKI, if `seal_state == sealed`, and in the Justfile
we disallow combinations that don't make sense, like BLS boot + sealed,
allowing missing verity (xfs) + sealed, etc.

Signed-off-by: Pragyan Poudyal <pragyanpoudyal41999@gmail.com>

diff --git a/contrib/packaging/seal-uki b/contrib/packaging/seal-uki
--- a/contrib/packaging/seal-uki
+++ b/contrib/packaging/seal-uki
@@ -13,6 +13,13 @@ secrets=$1
 shift
 allow_missing_verity=$1
 shift
+seal_state=$1
+shift
+
+if [[ $seal_state == "sealed" && $allow_missing_verity == "true" ]]; then
+    echo "Cannot have missing verity with sealed UKI" >&2
+    exit 1
+fi
 
 # Find the kernel version (needed for output filename)
 kver=$(bootc container inspect --rootfs "${target}" --json | jq -r '.kernel.version')
@@ -28,10 +35,12 @@ ukifyargs=(--measure
            --json pretty
            --output "${output}/${kver}.efi")
 
-# Signing options, we use sbsign by default
-ukifyargs+=(--signtool sbsign
-            --secureboot-private-key "${secrets}/secureboot_key"
-            --secureboot-certificate "${secrets}/secureboot_cert")
+if [[ $seal_state == "sealed" ]]; then
+    # Signing options, we use sbsign by default
+    ukifyargs+=(--signtool sbsign
+                --secureboot-private-key "${secrets}/secureboot_key"
+                --secureboot-certificate "${secrets}/secureboot_cert")
+fi
 
 # Baseline container ukify options
 containerukifyargs=(--rootfs "${target}")
